!set variable_substitution=true
!variables

CREATE OR REPLACE TASK CHEM_&{ENV}.BUSINESSANALYTICS.SUPPLY_CHAIN.​TSK_NOTIFICATION_DP_SUCCESS
    WAREHOUSE='CHEM_BUSINESS_WH'
    SCHEDULE='USING CRON */15 * 1-5 * * UTC'
AS CALL CHEM_&{ENV}.BUSINESSANALYTICS.SUPPLY_CHAIN.SP_NOTIFICATION_DP_TASK_SUCCESS();

!system echo " Successfully created task TSK_NOTIFICATION_DP_SUCCESS .... "
