!set variable_substitution=true  
!variables  

CREATE OR REPLACE TABLE CHEM_&{ENV}_BUSINESSANALYTICS.SUPPLY_CHAIN.TB_NOTIFICATION_FAILURE(  
    ID INTEGER,  
    QUERY_ID VARCHAR(50),  
    DATABASE_NAME VARCHAR(200),  
    SCHEMA_NAME VARCHAR(200),  
    TASK_NAME VARCHAR(200),  
    SP_NAME VARCHAR(200),  
    ERROR_CODE VARCHAR(10),  
    ERROR_MESSAGE VARCHAR,  
    COMPLETED_TIME TIMESTAMP_LTZ(3),  
    TEAM VARCHAR(200),  
    LOAD_TIME TIMESTAMP_LTZ(3)  
);  

!system echo " Successfully created table TB_NOTIFICATION_FAILURE ....."